pool: Hosted Ubuntu 1604

variables:
  # - group: AWS
  # - name: AWS_CLOUDFORMATION_STACK_NAME
  #   value: my-app-stack
  # - name: APP_NAME
  #   value: MY_APP

#container: rocket

steps:
- task: RocketBuildAndDeploy@0
  inputs:
    awsCredentials: 'cloud55'





# steps:
#   - script: |
#       rocket build-cfn-params --app-name $(APP_NAME) --template-file cloudformation/config/params.template

#     displayName: Build cloudformation params.json

#   - script: |
#       rocket deploy-stack $(AWS_CLOUDFORMATION_STACK_NAME) --template-file cloudformation/s3-template.yaml --params-file cloudformation/config/params.json

#     displayName: Deploy cloudformation stack