pool: Hosted Ubuntu 1604

resources:
  containers:
  - container: rocket
    image: cloud55/rocket:latest

variables:
  - group: AWS
  - name: AWS_CLOUDFORMATION_STACK_NAME
    value: my-app-stack
  - name: APP_NAME
    value: MY_APP

container: rocket

steps:
- script: |
    rocket build-cfn-params --app-name $(APP_NAME) --template-file cloudformation/config/params.template

  displayName: Build cloudformation params.json
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_KEY_ID: $(AWS_SECRET_KEY_ID)

- script: |
    rocket deploy-stack $(AWS_CLOUDFORMATION_STACK_NAME) --template-file cloudformation/s3-template.yaml --params-file cloudformation/config/params.json

  displayName: Deploy cloudformation stack
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_KEY_ID: $(AWS_SECRET_KEY_ID)

